"""Add description column to post table

Revision ID: 4ca227a0ef81
Revises: 6359ee182971
Create Date: 2025-04-12 14:56:51.242368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca227a0ef81'
down_revision = '6359ee182971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('published')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('description')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_column('published')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
